### ISSUE TITLE
Several warnings when building the future version

### ISSUE THREAD

**Issue by eribertomota** [resurrecting-open-source-projects/scrot#11]
Hi all,

When preparing the 0.10 version, I can  see that source code produces several warnings when building over Debian Sid.

I attached a log.

@daltomi Can you take a look over it?

Cheers,

Eriberto

[build.zip](https://github.com/resurrecting-open-source-projects/scrot/files/3270290/build.zip)

**Comment by daltomi** [comment]
I do not know what happens with git, but I can not create a PR without sending many changes.
Patch:
[fix_buid_warnings.patch.zip](https://github.com/resurrecting-open-source-projects/scrot/files/3270564/fix_buid_warnings.patch.zip)

**Comment by daltomi** [comment]
The correct branch for this fix es #14

**Comment by eribertomota** [comment]
Fixed by 7a3e323
