### ISSUE TITLE
inconsistent programming style

### ISSUE THREAD

**Issue by guijan** [resurrecting-open-source-projects/scrot#110]
Currently, scrot has no programming style. The C source files have become a mixture of many different styles.

In [src/slist.c](src/slist.c):
- 2 space indents
- explicit cast of malloc return value
- function definition block starts in the same line as the function declaration
- no space between ```while``` and its parentheses

Meanwhile, in [src/selection_edge.c](src/selection_edge.c):
- 4 space indents
- no explicit cast of calloc return value
- function definition block starts in its own line

And there's even a 3rd style in [src/main.c](src/main.c) which not all functions follow:
- 2 space indents
- function definition block starts in its own line
- function return value on its own line, separate from the function identifier
- no explicit cast of calloc return value

I suggest that scrot should have a single well defined style for all contributors to follow. 
This style should have a few desired properties:
1. easy to enforce
2. easy to convert the existing codebase to
3. easy to remember

The style I'm thinking would be the best for scrot is the [WebKit style](https://webkit.org/code-style-guidelines/).
This style is explained at length in the WebKit page, but it's very simple:
- 4 space indents
- function declarations and their linkages and return values in the same line
- goto labels at 0 indentation
- case jump labels in a switch statement have the same indentation level as the switch
- function definition's block starts in its own line
- pointers bind to the identifier, not the type
- conditional and loop blocks start on the same line as the conditional or the loop's parenthesized part
- there's always a space between a keyword and an open parentheses

I also suggest that the style should be made a little more strict, I have 2 rules to add which are not merely opinion based:
- no unneeded explicit casts
Clang and GCC hide warnings when an explicit cast is made. Always using explicit casts will always hide warnings in the statement with the cast, and could hide bugs.
A cast should only be made when necessary for this reason, the return values of malloc/calloc or the type of an assignment should never be cast.
- use the identifier and not the type in the sizeof operator
If you use the type and not the identifier, you could one day change the identifier's type and accidentally leave the sizeof operator's argument untouched, leading to a bug. When the identifier is used as the argument, such a bug is impossible.

In practice, this style is extremely similar to K&R style, only its indentation is 4 spaces instead of an 8-column tab. The style is also almost the same as the "official" style used in the Golang programming language. It shouldn't be too foreign to a large quantity of C programmers.

The LLVM people have produced a tool called ```clang-format``` which automatically converts source code to a style, and this tool comes with the WebKit style by default.
Sadly, I have already confirmed ```clang-format``` is incomplete and can change the semantics of the source. This is unfortunately common with source formatters, I tried it and got a build failure. It also did not fully make the source compliant to the WebKit style, immediately I can see '*' characters aligning to the type rather than the identifier. 

This change would have to be done by changing each individual file with the ```clang-format``` tool and fixing any bugs that crop up, then making a PR.

If this suggestion is accepted, our CONTRIBUTING.md will have to be updated, the list of files to be converted to the new style will be added to our TODO, and the style should be enforced for all new commits.

**Comment by keysym** [comment]
I'm poking around with [https://github.com/resurrecting-open-source-projects/sniffit](sniffit) and it also has no style defined. Would be great to have style rules on all Resurrecting Open Source Projects as well!

**Comment by eribertomota** [comment]
> I'm poking around with [https://github.com/resurrecting-open-source-projects/sniffit](sniffit) and it also has no style defined. Would be great to have style rules on all Resurrecting Open Source Projects as well!

Unfortunately, I can't impose a style for all projects because I am not a programmer. Consequently, I am not able to check if a style is followed by people. However, if you are a good programmer and if you want work seriously over sniffit, you can define a style. Taking advantage of this theme, I would like to see someone working over [packit](https://github.com/resurrecting-open-source-projects/packit), a very nice and very useful project.

**Comment by daltomi** [comment]
@guijan Yes I like the idea. 

> This change would have to be done by changing each individual file with the `clang-format` tool and fixing any bugs that crop up, then making a PR.

I recommend that the title of the PR have a prefix, `code style:` or something like that

**Comment by guijan** [comment]
Initial PR up at #116

**Comment by guijan** [comment]
Thanks for everything, now it's only a matter of doing the work. It's written down in [TODO.md](TODO.md)
