### ISSUE TITLE
[Feature Request] Add option to write image to standard output

### ISSUE THREAD

**Issue by E1k3** [resurrecting-open-source-projects/scrot#112]
Would it be possible to add an option for scrot to write the screenshot to standard output to avoid the image from reaching the filesystem?

I have seen scrot being used to capture screenshots for lock screens and since `/tmp` is not always in memory, these screenshots may reach the HDD and could be recovered later. This would be avoided by piping the image directly to the image processing (usually blur or pixelation).

I have tried process substitution in zsh (`scrot >(image_processing_cmd)`), but I only got `giblib error: Saving to file /proc/self/fd/12_000 failed` as a result.

**Comment by daltomi** [comment]
Doesn't this work for you?
```bash
scrot --overwrite /dev/stdout
```

**Comment by daltomi** [comment]
Example, optimize with `pngquant`:
```bash
scrot -o /dev/stdout | pngquant -o file.png -
```

**Comment by E1k3** [comment]
Thank you, apparently, the -o / --overwrite flag was all I was missing. Process substitution works with it as well:
`scrot -o >(image_processing_cmd)`

I think the error message when "overwriting" files without the `-o` flag could be better, but thats nitpicking.
This can be closed.

**Comment by daltomi** [comment]
I'm glad you've solved.
Cheers.

**Comment by daltomi** [comment]
TODO: For future reference before adding an example to the manual: `scrot -o > file.png` does not work, create an empty file.

**Comment by E1k3** [comment]
Not sure where you are going with this, but `scrot -o /dev/stdout > file.png` would work.

**Comment by daltomi** [comment]
Yes I know, but one would hope that the other way would work too, right?

**Comment by E1k3** [comment]
Since -o is the overwrite flag and not the output flag, I would not expect `scrot -o > file.png` to work.

What I expect from experience with other CLI tools, is that an output path of `-` results in an output to STDOUT.

So something like this: `scrot - > file.png`

-o would be implicit in that case because output to STDOUT is impossible without overwriting.

Other programs that follow this pattern include cat (for standard input), ffmpeg and gzip (for standard input and output).

**Comment by daltomi** [comment]
Yes you're right.
