### ISSUE TITLE
Fedora support?

### ISSUE THREAD

**Issue by OmiceyO** [resurrecting-open-source-projects/scrot#151]
Did anyone have success installing this in Fedora 34?

**Comment by eribertomota** [comment]
Do you are trying to install master branch or last release (scrot-1.6)?

I don't know well Fedora but I just created a Fedora 34 in a VM and scrot 1.6 built fine.  What is the problem that you found?

```
dnl install autoconf-archive automake imlib2-devel libXcomposite-devel libXfixes-devel pkg-config
./autogen.sh
./configure
make
make install
scrot -v
scrot version 1.6

```

**Comment by OmiceyO** [comment]
Some package was missing and i needed the -devel version instead of the regular one. It works fine now! Thanks!

**Comment by eribertomota** [comment]
Cool! Have a nice day.
