### ISSUE TITLE
Make libXcomposite, libXext and libxfixes optional

### ISSUE THREAD

**Issue by TAAPArthur** [resurrecting-open-source-projects/scrot#163]
libXcomposite is only used for the function `scrot_grab_stack_windows` in main.c. It seems reasonable for this to be able to be compiled out. As I'm writing this, I realize the same argument could be made for libXext and libxfixes since they only affect `scrot_grab_mouse_pointer`. I feel like it is better for scrot to build and lose these two function than failing to build.

As a quick test, I just removed the body of the affected methods and updated the Makefile to not include the libraries and normal operations seem to work fine.

**Comment by daltomi** [comment]
These features (`--pointer`, `--stack`) are already in scrot a long time ago , remove them would create just problems:

1) This would change the behavior that is available so far in the user space.

2) Give the option to a maintainer of a distribution to opt if he wants or not those options: for example an ArchLinux mantainer  "feels" that he does not like the option of capturing the mouse, now hundreds of users stay without that option, to same time the maintainer of Fedora feels that he likes that option and enables it, what do we have? A scrot 1.7 release with different behavior !!

And who is going to pay broken dishes? We, when users become open a issues saying: "I do not know what happens but in Fedora I can capture the mouse cursor, but not on Archlinux, help me ..." 

Your proposal looks more like a requirement of yours that some scrot needs. 
Do you have a technical reason why you can not use those libraries?

**Comment by TAAPArthur** [comment]
I don't have a technical reason. I just try to minimize unused libraries/dependencies and these 3 seemed "optional" in my opinion. Or at least installing 1-3 extra libraries for features that won't be used isn't ideal to me. I'm on a source based distro so patching them out is perfectly viable for me and on the flip side building unneeded software adds up quickly. I just first looked for configure flags to disable them was surprised not to see them. Didn't know if this was intentional or not so opened an issue.

In regards to the second point, I feel that is unavoidable to a certain extent. Some distros just patch the software the package. I believe Kiss and Void do so in some cases. Seen the latter apply simple patches and the former remove dependencies that didn't meet their standard like dbus or gettext. Some programs get around the confusion by including configure options in their verbose version output. Since the problem of different packagers building with different flags is pretty common. Can't comment if it is worth the possible headache to you, but would have assumed that most maintainers wouldn't add flags to reduce features for existing packages. But I have no data to back that up.

**Comment by daltomi** [comment]
> I don't have a technical reason. I just try to minimize unused libraries/dependencies and these 3 seemed "optional" in my opinion.

Then your proposal does not benefit the project, neither the user , it would only add development complications. After removing what you do not like with a PR I am sure you will send others and others mutilate the code everywhere just because you do not like I do not know what and then someone will have to maintain, sooner or later.

**Comment by TAAPArthur** [comment]
I think a simple "no thank you" would have have been sufficient. You know instead of the personal attack and denying my existence (since I am also a user). It was just a suggestion.
