### ISSUE TITLE
scrot with -e command to copy to clipboard stopped working

### ISSUE THREAD

**Issue by snprajwal** [resurrecting-open-source-projects/scrot#182]
I use `scrot -z -s '/home/user/%d%b-%H%M.png' -e 'xclip -selection clipboard -t image/png $f'` to take a screenshot and put it to my clipboard, so that I can share it on emails and chats easily. This stopped working a day or two ago, and I'm not really sure why.

Distro: Arch Linux
Kernel: 5.16.1-arch1-1
Scrot version: 1.7

**Comment by snprajwal** [comment]
Working with scrot 1.7-1

**Comment by devansh08** [comment]
I'm on Arch as well but `$f` inside `-e` is always returning empty for me. Was this the issue you had as well ? Even something as simple as `echo $f` is returning empty values.

I checked that I do have scrot 1.7-1 installed from pacman, even though `scrot --version` says 1.7. Any ideas ?

**Comment by daltomi** [comment]
Please confirm that you don't have a syntax error in the shell.
This should work: `scrot -e 'echo $f' `
The following of course not: `scrot -e "echo $f"`

**Comment by devansh08** [comment]
Oh... Sorry for my late response.

Yes you are right I've been using double quotes all along! Did not realize it would have been using my shell's `f` variable instead. Thanks for clarifying!
