### ISSUE TITLE
On some apps, scrot -s adds a white border

### ISSUE THREAD

**Issue by hydrargyrum** [resurrecting-open-source-projects/scrot#191]
scrot -s allows to select an area to screenshot. Sometimes, it adds a white border to the screenshot (see attached picture), possibly it does not erase the selection rectangle before screenshoting. It happens especially on some electron apps.

![2022-05-31-102206_415x166_scrot](https://user-images.githubusercontent.com/2804645/171127346-113102a6-4082-410c-a1b5-03c1fcf1767e.png)

**Comment by hydrargyrum** [comment]
@daltomi, Indeed that fixes it. Now that I search the right keyword (`edge`) on the bugtracker, there are several issues on the subject.

1. Maybe add some FAQ? Maybe as a pinned issue
2. Maybe make edge the default mode?

**Comment by daltomi** [comment]
The FAQ is in progress: #189
