### ISSUE TITLE
scrot not supporting multiple displays

### ISSUE THREAD

**Issue by eribertomota** [resurrecting-open-source-projects/scrot#2]
Bug from Debian[1]:

Trying to use scrot -m or --multidisp doesn't appear to work. Man page 
says it should grab a shot from each display and then merge the image, 
however it only appears to be taking a shot from one. Is there something
else that has to be configured/installed to allow this to work?

[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=861907

**Comment by daltomi** [comment]
More information is required. Use the `xrandr` utility and show the result.

**Comment by ifohancroft** [comment]
Is it possible to screenshot just a single monitor on a multiple monitor setup that runs on a single X screen?

**Comment by eribertomota** [comment]
This issue is no longer present in scrot and was closed in Debian.
