### ISSUE TITLE
Multiple bugs in scrot

### ISSUE THREAD

**Issue by guijan** [resurrecting-open-source-projects/scrot#215]
This is a general issue for tracking bugs I've found but not put in the work to fix before I forget them.

# Currently unfixed
## access()
The `access()` function suffers from a [time of check to time of use](https://en.wikipedia.org/wiki/Time-of-check_to_time-of-use) issue. Nothing guarantees us that what `access()` could access will be there when we try to `open()`, or that what it couldn't access won't be there. The code shouldn't ask if it can do something, it should just do it and check the return value. This function shouldn't exist and its callers should be reviewed:
https://github.com/resurrecting-open-source-projects/scrot/blob/70a7540cfdc1000db8d400883c2eece386b5bf91/src/options.c#L332-L336
`access()` is also used elsewhere, use grep to find the uses:
https://github.com/resurrecting-open-source-projects/scrot/blob/70a7540cfdc1000db8d400883c2eece386b5bf91/src/scrot.c#L486
https://github.com/resurrecting-open-source-projects/scrot/blob/70a7540cfdc1000db8d400883c2eece386b5bf91/src/scrot.c#L455

## `scrot --delay` time drift
The implementation of the --delay option calls `sleep()` in a loop, time passes between each `sleep()` call, so it drifts. 
https://github.com/resurrecting-open-source-projects/scrot/blob/70a7540cfdc1000db8d400883c2eece386b5bf91/src/scrot.c#L262-L281
Edit: setitimer() fixes this but is extremely difficult to use. clock_nanosleep() also fixes it but is not widely implemented. Most timer APIs in POSIX are broken in some way or another, and the fixed versions are not widely implemented, so this will have to wait. There was an attempt at #218.

## Maximum filename length is wrong
Scrot uses this macro to check if input/output filenames are within a certain size:
https://github.com/resurrecting-open-source-projects/scrot/blob/70a7540cfdc1000db8d400883c2eece386b5bf91/src/options.c#L61-L66
https://github.com/resurrecting-open-source-projects/scrot/blob/70a7540cfdc1000db8d400883c2eece386b5bf91/src/options.c#L76

The issue is that a maximum length of 256 is hardcoded, but the maximum filename length is a very complex issue. 256 could be too much or too little depending on the operating system, the file system, and even what directory the file is created in. The solution is that the code handling input/output filenames should pass around an alloc storage duration buffer and dynamically grow it as needed throughout the program's execution. Then, when the file is finally created, the system will return error if it fails to create the file.

Also, that code didn't have to be a macro.

# Currently being worked on

## alloc
It appears the return value of the allocation functions still isn't checked everywhere:
https://github.com/resurrecting-open-source-projects/scrot/blob/70a7540cfdc1000db8d400883c2eece386b5bf91/src/scrot.c#L472-L473

A more convoluted case:
https://github.com/resurrecting-open-source-projects/scrot/blob/70a7540cfdc1000db8d400883c2eece386b5bf91/src/options.c#L329
https://github.com/resurrecting-open-source-projects/scrot/blob/70a7540cfdc1000db8d400883c2eece386b5bf91/src/options.c#L656
Scrot's use of `assert()` is wrong here and probably in other places too, checking if `malloc()` returned error isn't only for debug builds.

It's very much possible for the allocation functions to return error, even on systems that overcommit like Linux and the BSDs:
```c
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

int
main(void)
{
	void *p;
	if ((p = malloc((size_t)-1)) == NULL)
		puts("can't malloc SIZE_MAX");
	else
		puts("can malloc SIZE_MAX");
	pause(); /* Go inspect the virtual/physical memory usage. */
	free(p);
}
```
OpenBSD output:
![2023-01-25-231635_220x40_scrot](https://user-images.githubusercontent.com/25590950/214713969-f180b030-e3ef-4aa9-bd63-de4b37b478be.png)
In the real world, it's probably only going to happen on 32-bit, but don't worry about implementation details, just check the possible errors that the C allocation functions are documented to return.

Putatively fixed by #222 #242

## Path of stdout
We don't need to know the path of stdout. It doesn't even necessarily have one. The code suffers from the same TOCTTOU mentioned above. It also uses __/proc__ which is a Linux extension and the code is still present on non-Linux systems, so it's possible to affect the behavior of scrot by creating a __/proc/self/fd/1__ file on non-Linux systems. 
https://github.com/resurrecting-open-source-projects/scrot/blob/70a7540cfdc1000db8d400883c2eece386b5bf91/src/options.c#L338-L358

This is probably because the imlib APIs we use want an output filename instead of an output file descriptor which is a design bug in imlib because it creates more races and unnecessarily limits the usefulness of the library. I looked at the headers of Imlib 1.10.0 and there is no function that writes an image to a given fd.

Imlib has added a function to address this in 1.11.0, we need to migrate to it.

# These have been fixed
## `scrot --delay` shortening
Sending SIGALRM to scrot while it waits causes sleep() to return early, and scrot then sleeps less than requested.

Fixed by #224

**Comment by daltomi** [comment]
Much to discuss.
We are going to see it little by little, you know, everyone's free time. Thanks.

Btw, `Imlib2` uses `access()` too.

**Comment by guijan** [comment]
I'll work on fixing the scrot --delay time drift issue.

**Comment by N-R-K** [comment]
For the allocation issue - I think having wrappers like `emalloc` `ecalloc` etc - which abort or failure - is the most practical solution IMO.

**Comment by N-R-K** [comment]
> The issue is that a maximum length of 256 is hardcoded, but the maximum filename length is a very complex issue. 256 could be too much or too little depending on the operating system, the file system, and even what directory the file is created in.

There exist a posix macro `NAME_MAX` ([limits.h](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/limits.h.html#tag_13_23)) but it suffers from the [same issues as `PATH_MAX`](https://eklitzke.org/path-max-is-tricky).

But in any case, I don't believe 256 can be "too much" because POSIX defines NAME_MAX as at least 255 bytes (excluding the nul-byte) - but it can be "too little".

> The solution is that the code handling input/output filenames should pass around an alloc storage duration buffer and dynamically grow it as needed throughout the program's execution.

As far as I see, it's already using `strdup`. So the check seems to be more of a sanity check and probably can be removed (assuming the file-creation site is properly error-checked).

https://github.com/resurrecting-open-source-projects/scrot/blob/4c59bd454f51401a22820d3a38973475da93cda4/src/options.c#L628-L629

https://github.com/resurrecting-open-source-projects/scrot/blob/4c59bd454f51401a22820d3a38973475da93cda4/src/options.c#L227-L229

**Comment by guijan** [comment]
>There exist a posix macro NAME_MAX ([limits.h](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/limits.h.html#tag_13_23)) but it suffers from the [same issues as PATH_MAX](https://eklitzke.org/path-max-is-tricky).
>But in any case, I don't believe 256 can be "too much" because POSIX defines NAME_MAX as at least 255 bytes (excluding the nul-byte) - but it can be "too little".

Yeah, and we have fpathconf() to get the maximum lengths in a specific directory (pathconf() suffers from TOCTTOU).

Unfortunately, it's not so simple. If you have a directory with a path that is 4000 bytes and PATH_MAX is 4096, you might not be able to create a file with a name larger than 96 bytes inside that directory. The easiest way to do things is to just let filenames grow as needed inside the code and then let the relevant system functions return error to tell us if it's too long.

It's also possible that NAME_MAX is flat out wrong. Linux and BSD can mount a FAT filesystem with LFN disabled, that means filenames are at most 11 bytes long (8.3 format):
https://linux.die.net/man/8/mount (CTRL+F "check=value")
http://man.openbsd.org/mount_msdos#s (option -s)

**Comment by N-R-K** [comment]
> This is probably because the imlib APIs we use want an output filename instead of an output file descriptor

That seems to be the case.

> I looked at the headers of Imlib 1.10.0 and there is no function that writes an image to a given fd.

It didn't have reading files from fd/memory either until recently. But people asked for it and it got added. If you ask for a "save to FILE */fd" feature - then there's a high chance it'll get accepted too :)

**Comment by N-R-K** [comment]
I think the unchecked alloc issues should have been fixed by dec18930b5961e88dd88f154ffecb696ab1fb832. Unless there's more remaining.

**Comment by guijan** [comment]
Still there.
https://github.com/resurrecting-open-source-projects/scrot/blob/27da772c0d64e26fba5d1159daf39cf56db5aa26/src/options.c#L325-L331
Use grep to find the other `strndup()` calls.

That one also seems to leak memory, it's the same class of errors as the leaks we've found recently: pass `-C` multiple times and it'll leak as many window class names as `-C` was repeated.

**Comment by guijan** [comment]
Editing this issue is annoying, I should have made several, like I already did with the dozen other bugs I found. I'll make more issues and then close this one.
