### ISSUE TITLE
keep aspect ratio for thumb

### ISSUE THREAD

**Issue by eworm-de** [resurrecting-open-source-projects/scrot#216]
I use to run this command to capture the screen, including a thumb:
```
scrot --thumb 100x0 /tmp/screen.png
```

The thumb used to have a width of 100 pixels, preserving the correct aspect ration. This broke with ff88b0b0cd38137113319cb86e423cb1fe4d6b3a (I think, to be verified...) and returns an error message now:
```
scrot: option --thumb: resolution height '0' is too small
```

Can we define a special case for value `0` and have the old behavior back?

**Comment by guijan** [comment]
I've just tried the example invocation with both commit ff88b0b0cd38137113319cb86e423cb1fe4d6b3a and the preceding ae4deba4772f543842933184722aeb77b49496cd, and indeed, the change in behavior was introduced by ff88b0b0cd38137113319cb86e423cb1fe4d6b3a.

**Comment by eworm-de** [comment]
Will you take care of this or should I have a look myself?

**Comment by guijan** [comment]
Yes, I'll fix it.

I'm about to go to sleep but I'll be adding this feature back and documenting it, hopefully there will be a PR today.

Did you find out about it by reading the source code?

**Comment by eworm-de** [comment]
Found out what, that it works or that it breaks? 😜

Other tools support this or something similar, for example imagemagick:
https://imagemagick.org/script/command-line-processing.php#geometry

So I did just try and it worked.

Well, now it broke. 😝

**Comment by eworm-de** [comment]
Do not worry! This functionality was undocumented, so there was no reason for you to test it.

Nevertheless it would be nice to have the behavior back.
