### ISSUE TITLE
resurrect/retire giblib as well?

### ISSUE THREAD

**Issue by mathstuf** [resurrecting-open-source-projects/scrot#22]
Thanks for bringing this back. However, it depends on `giblib` which is still abandoned. Should this repo remove the dependency or should the org bring back `giblib` as well?

**Comment by eribertomota** [comment]
Thanks for your message @mathstuf.

@daltomi What you think about it?

Regards,

Eriberto

**Comment by jda** [comment]
I noticed that the giblib string and mem functions are [very similar to this file](https://chromium.googlesource.com/chromiumos/third_party/ktop/+/refs/heads/master/eprintf.c) in Chromium, which is attributed to a book:

> Excerpted from 'The Practice of Programming' by Brian W. Kernighan and Rob Pike

Anyway, I have a branch where I use it instead of the giblib string functions: https://github.com/jda/scrot/commit/6b81b38cf7b358575aa020173e424fa30173d36e
Will look at the gib_imlib functions next.

**Comment by eribertomota** [comment]
Em seg, 5 de ago de 2019 às 02:29, Jade Auer <notifications@github.com>
escreveu:

> I noticed that the giblib string and mem functions are very similar to
> this file
> <https://chromium.googlesource.com/chromiumos/third_party/ktop/+/refs/heads/master/eprintf.c>
> in Chromium, which is attributed to a book:
>
> Excerpted from 'The Practice of Programming' by Brian W. Kernighan and Rob
> Pike
>
> Anyway, I have a branch where I use it instead of the giblib string
> functions: jda@6b81b38
> <https://github.com/jda/scrot/commit/6b81b38cf7b358575aa020173e424fa30173d36e>
> Will look at the gib_imlib functions next.
>
>
>
Thanks Jade!

**Comment by mathstuf** [comment]
What's the progress here? Can an external-giblib-free release be made within the next few months?

**Comment by daltomi** [comment]
Hi.
My first attempt, to **embed** it in `scrot` was wrong: #24 

It is true that it is discontinued, but replacing it in `scrot` I do not think necessary, it is much "reinvent the wheel" and as far as I know it has no bugs.
In any case I like the idea that may be in the `resurrecting-open-source-projects`

If someone does want to replace it, here is a list of the functions that are used from `scrot`:
```
[gib_list.c]
gib_list_*
	<build-in> 508 LOC

Note: scrot calls 2 functions:
	gib_list_add_end
	gib_list_length

[gib_utils.c]
gib_eprintf
	fflush
	fprintf
	va_start
	vfprintf
	va_end
	strlen
	strerror
	exit

gib_weprintf
	fflush
	fprintf
	va_start
	vfprintf
	va_end
	strlen
	strerror

gib_emalloc
	malloc
	<gib_eprintf>
	
gib_estrdup
	malloc
	<gib_eprintf>
	strcpy

[gib_imlib.c]
gib_imlib_create_image_from_drawable
	imlib_context_set_drawable
	imlib_create_image_from_drawable

gib_imlib_save_image_with_error_return
	imlib_context_set_image
	strrchr
	imlib_image_set_format
	imlib_save_image_with_error_return

gib_imlib_image_get_width:
	imlib_context_set_image
	imlib_image_get_width

gib_imlib_image_get_height
	imlib_context_set_image
	imlib_image_get_height

gib_imlib_create_cropped_scaled_image
	imlib_context_set_image
	imlib_context_set_anti_alias
	imlib_create_cropped_scaled_image

gib_imlib_save_image_with_error_return
	imlib_context_set_image
	strrchr
	imlib_image_set_format
	imlib_save_image_with_error_return

gib_imlib_free_image_and_decache
	imlib_context_set_image
	imlib_free_image_and_decache

gib_imlib_image_format
	imlib_context_set_image
	imlib_image_format

gib_imlib_image_fill_rectangle
	imlib_context_set_image
	imlib_context_set_color
	imlib_image_fill_rectangle

gib_imlib_blend_image_onto_image
	imlib_context_set_image
	imlib_context_set_anti_alias
	imlib_context_set_dither
	imlib_context_set_blend
	imlib_context_set_angle
	imlib_blend_image_onto_image
```

**Comment by mathstuf** [comment]
Thanks, I had missed that PR since it was just a commit reference, not a full PR reference. I think embedding might still be valid if scrot is indeed the last user of giblib (adopting it directly rather than keeping an external dep that nothing else uses).

**Comment by jda** [comment]
I commented on #24 re: vendoring giblib. Basically, other utils have directly included it already, but I don't think we are using nearly enough from it to justify keeping it.

Since it's the US holiday season I've had some time to pick this up again and have all the gib functions removed except for their linked list implementation and am currently toying with replacing that with `sys/queue.h`

**Comment by ifohancroft** [comment]
Since giblib is a wrapper around imlib2, won't the easiest/best way to remove the dependency on giblib be to use imlib2 directly?

**Comment by ifohancroft** [comment]
> I commented on #24 re: vendoring giblib. Basically, other utils have directly included it already, but I don't think we are using nearly enough from it to justify keeping it.
> 
> Since it's the US holiday season I've had some time to pick this up again and have all the gib functions removed except for their linked list implementation and am currently toying with replacing that with `sys/queue.h`

I am interested in what's the idea/plan for getting rid of giblib as a dependency.
Will it be included or will it be bypassed?
I mean for example it mostly requires imlib2 (the rest of its dependencies (freetype2 and libxext) are required by imlib2 anyway) so will scrot just start using imlib2 directly?

**Comment by marmarek** [comment]
What is the state of this? giblib is already unavailable in Fedora (31 and 32), which makes scrot not installable there.

**Comment by eribertomota** [comment]
Currently, no one working over this issue. We need volunteers to fix this
issue.
