### ISSUE TITLE
scrot --delay drift

### ISSUE THREAD

**Issue by guijan** [resurrecting-open-source-projects/scrot#245]
The implementation of the --delay option calls `nanosleep()` in a loop, time passes between each `nanosleep()` call, so it drifts. 
https://github.com/resurrecting-open-source-projects/scrot/blob/27da772c0d64e26fba5d1159daf39cf56db5aa26/src/scrot.c#L286-L302
https://github.com/resurrecting-open-source-projects/scrot/blob/27da772c0d64e26fba5d1159daf39cf56db5aa26/src/scrot.c#L275-L284
`setitimer()` fixes this but is extremely difficult to use and at the very least Linux and OpenBSD have implementation bugs in that function. `clock_nanosleep()` also fixes it but is not implemented on OpenBSD and OS X. It's possible to implement an imitation `clock_nanosleep()` that's good enough for our uses with the standard `pthread_condtimedwait()` but OS X doesn't implement that function either. 

Most timer APIs in POSIX are broken in some way or another, and the better ones are not widely implemented, so this will have to wait. There was an attempt at #218.

**Comment by guijan** [comment]
I wrote a program to measure the timing error caused by calling `nanosleep()` in a loop.
```c
#include <errno.h>
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

static void timespec_sub(struct timespec *, struct timespec *,
    struct timespec *);

/* This program measures the timing error caused by calling nanosleep in a loop.
 * It also prints a countdown to imitate scrot's countdown code.
 */
int
main(int argc, char *argv[])
{
	long long sleep;
	char *p;
	struct timespec tmp, start, end, elapsed;
	long long i;
	double a, b;

	if (argc == 1) {
		sleep = 5;
	} else if (argc == 2) {
		sleep = strtoll(argv[1], &p, 10);
		if (*argv[1] == '\0' || *p != '\0'
		    || (errno == ERANGE && (sleep == LONG_MAX || sleep < 0)))
			exit(1);
	} else {
		exit(1);
	}

	tmp.tv_sec = 1;
	tmp.tv_nsec = 0;
	clock_gettime(CLOCK_MONOTONIC, &start);
	for (i = sleep; i > 0; i--) {
		dprintf(1, "%lld\n", i);
		nanosleep(&tmp, NULL); /* can't EINTR, no signal handler. */
	}
	clock_gettime(CLOCK_MONOTONIC, &end);

	/* Now print information about the clock drift. */
	timespec_sub(&end, &start, &elapsed);
	printf("Requested sleep: %llds\n", sleep);
	printf("      Slept for: %lld.%0.3lds\n", (long long)elapsed.tv_sec,
	    elapsed.tv_nsec / 1000000 /* Too much precision, reduce to ms. */);
	tmp.tv_sec = sleep;
	tmp.tv_nsec = 0;
	timespec_sub(&elapsed, &tmp, &tmp);
	printf("     Difference: %lld.%0.3lds\n", (long long)tmp.tv_sec,
	    tmp.tv_nsec / 1000000);
	a = sleep;
	a *= 1000000000;
	b = elapsed.tv_sec;
	b *= 1000000000;
	b += elapsed.tv_nsec;
	printf("    Difference%%: %.3lf%%\n", 100 - a / b * 100);
}

/* Ripoff of the BSD timespecsub macro. */
static void
timespec_sub(struct timespec *a, struct timespec *b, struct timespec *result)
{
	result->tv_sec = a->tv_sec - b->tv_sec;
	result->tv_nsec = a->tv_nsec - b->tv_nsec;
	if (result->tv_nsec < 0) {
		result->tv_sec--;
		result->tv_nsec += 1000000000;
	}
}
```
I've compiled it with `cc -O3` and tried it in 1 bare metal operating system and 2 operating systems inside a virtual machine, on my Core i7 4770 machine. Here's the output:
OpenBSD:
```plain
Requested sleep: 60s
      Slept for: 60.616s
     Difference: 0.616s
    Difference%: 1.018%
```
Alpine Linux inside OpenBSD's vmd (virtual machine daemon):
```plain
Requested sleep: 60s
      Slept for: 62.225s
     Difference: 2.225s
    Difference%: 3.576%
```
Hyperbola Linux inside OpenBSD's vmd:
```plain
Requested sleep: 60s
      Slept for: 62.211s
     Difference: 2.211s
    Difference%: 3.555%
```
Virtual machines have timing issues, so they represent a really bad case.

Here's the output of the program inside MSYS2 in a laptop with an Athlon II P320 running Windows 10:
```plain
Requested sleep: 60s
      Slept for: 60.483s
     Difference: 0.483s
    Difference%: 0.799%
```

I wonder what the timings look like on extremely toasty hardware like this https://yewtu.be/watch?v=4J-fKTspVgo ? You can see the individual lines in NetBSD's boot process being rendered in the video, calling dprintf() between iterations will skew the timings.

**Comment by N-R-K** [comment]
The loop and the dprintf only happens in practice if user requested countdown (yes, in theory the EINTR loop too). If the user requests countdown, it's pretty fair to assume that the use-case is interactive and a little bit of skew isn't even going to be noticeable.

(and yes, there's no real guarantee the skew will be little the same way there's no real guarantee that nanosleep won't miss the deadline by an hour because it only guarantees sleep for _at least_ amount of time, not at max).

As I said back in https://github.com/resurrecting-open-source-projects/scrot/pull/218, it's fine it can be solved easily. But it's not worth adding non-trivial (and/or non-initiative)  amount of code to fix things that aren't a problem in practice.

**Comment by guijan** [comment]
`XOpenDisplay()` can talk over the network and add even more delay, plenty of toaster hardware can run an X server and a modern OS even if it runs a terminal emulator slowly and imposing hardware requirements to reduce lines of code is not the way to go, virtual machines can make things worse, and a proper API like `clock_nanosleep()` can get rid of more error than just the error introduced by calling `nanosleep()` in a loop and simultaneously improve the timing on a fast machine and local X server. Plenty of reason to fix it even if it adds complexity.

`setitimer()` doesn't comply with POSIX on Linux and OpenBSD and it's hard to test it on other platforms to make sure they're not broken, and that PR was going nowhere, that's why I closed it. But that bug still has to be fixed.

Maybe we could use `clock_nanosleep()` if it's available, otherwise use `clock_gettime()` to correct drift and then call `nanosleep()`.
