### ISSUE TITLE
imPrintf goes out of bound

### ISSUE THREAD

**Issue by N-R-K** [resurrecting-open-source-projects/scrot#252]
If the last character of a filename is `$` or `\` then the `c` pointer can end up advancing past the end of the string.

https://github.com/resurrecting-open-source-projects/scrot/blob/7932f280d798cdb1d29174963e17cd41f6ce6691/src/scrot.c#L670-L672

Assuming `$` was the last character, this will push `\0` into `ret` and then `c` will be incremented past the end of the string on the next loop iteration.

**Comment by guijan** [comment]
I haven't looked deeply into the code yet but a pointer to one past the end of an object isn't UB.
