### ISSUE TITLE
`scrot -f` shouldn't "work"

### ISSUE THREAD

**Issue by guijan** [resurrecting-open-source-projects/scrot#263]
Scrot's `-f` option modifies `-s`'s behavior. However, if you specify just `-f` by itself, scrot goes on as usual. I'm a fan of strict option parsing, this should error. There are many other cases like this in the program, like `-b` or `-c`.

**Comment by N-R-K** [comment]
It's possible that someone has aliased scrot to something like: `scrot -b -c -f` or similar. This way if he does `scrot -s` the `bcf` flags act as "defaults". Otherwise if no `-s` was specified, it goes on as usual.

If we start erroring out then it'll be much more difficult to accomplish that.
