### ISSUE TITLE
`-l opacity` does not work as documented

### ISSUE THREAD

**Issue by mimuki** [resurrecting-open-source-projects/scrot#281]
According to the man page, running a command like `scrot -s -l width=8,color="#ff79c6",opacity=255,mode=edge` should result in an opaque pink border, and should be not transparent at all.

Instead, `opacity=255` is slightly see through, but `opacity=100` *is* completely opaque.

I'm not familiar with C and might be misunderstanding this line, but it looks like this isn't a bug, just the documentation being wrong. 
https://github.com/resurrecting-open-source-projects/scrot/blob/5ef8a82612a57ebd8b70cc45eaea437cbcfed741/src/selection_edge.c#L79

**Comment by N-R-K** [comment]
I can't really find any documentation on `_NET_WM_WINDOW_OPACITY` - it's not described in EWMH and seems to be something non-standard. Only thing I found was [this comment](https://github.com/tcltk/tk/blob/f7356543f35d404bef87be35b949bce5c4b168b6/unix/tkUnixWm.c#L1264) in Tk source code which suggest the atom works by mapping `[0x0, 0xFFFFFFFF]` to `[0%, 100%]` transparency.

If that's the case, then the bug I think is in the source code. Not the documentation.

**Comment by N-R-K** [comment]
This will be hard for me to fix because I don't use a compositor. If you change that line to the following:

```c
	unsigned long opacity = opt.lineOpacity * (0xFFFFFFFFu / 255);
```

does that work as expected?

If my understanding of `_NET_WM_WINDOW_OPACITY` is correct, then it should work. But I'll need  help from people who can actually test it out and report back :)

**Comment by daltomi** [comment]
The opacity values for the 'edge' selection mode is between 10% and 100%
At some point the function call was removed:
```
int const lineOpacity = optionsParseRequireRange(opt.lineOpacity, 10, 100);
```

**Comment by N-R-K** [comment]
It was:

```c
    const int lineOpacity = optionsParseRequireRange(opt.lineOpacity,
            SELECTION_EDGE_OPACITY_MIN, SELECTION_OPACITY_MAX);
```

The `SELECTION_EDGE_OPACITY_{MIN,MAX}` constants got removed in ff88b0b0cd38137113319cb86e423cb1fe4d6b3a for some reason.

**Comment by N-R-K** [comment]
> The opacity values for the 'edge' selection mode is between 10% and 100%

@daltomi What do you think should be done?

1. Change the code back to using [10, 100] for `edge` and fix the manpage.
2. Change the code to use [0, 255] as documented in the manpage.

IMO 2 is a better option since it will be consistent with the `opacity` range of `classic` as well.

**Comment by daltomi** [comment]
El Fri, 26 May 2023 02:12:24 -0700
NRK ***@***.***> escribió:
> 1. Change the code back to using [10, 100] for `edge` and fix the manpage.
> 2. Change the code to use [0, 255] as documented in the manpage.

Yes, I also agree with option 2, TIA.
