### ISSUE TITLE
scrot: received DestroyNotify event

### ISSUE THREAD

**Issue by daltomi** [resurrecting-open-source-projects/scrot#319]
Branch: 0d2e5ef2e72b9bc1880acf58ad13b0095ce38f73
Executing the `edge` line mode and with another selection mode the message is received.
```bash
scrot --select=hide --line mode=edge
scrot: received DestroyNotify event
```
 It was introduced here: #267

**Comment by N-R-K** [comment]
https://github.com/resurrecting-open-source-projects/scrot/pull/304 should fix this issue.
