### ISSUE TITLE
scrot -w $WINDOWID ?

### ISSUE THREAD

**Issue by peterbillam** [resurrecting-open-source-projects/scrot#34]
I'd like to run scrot from within a program, and the program is running
within a window which might be focussed (scrot -u :-)) but might not be :-(
I would really like a  -w  option to specify the WINDOWID
Would there be any chance of this happening ?

**Comment by daltomi** [comment]
Hi,
I was doing some tests and some problems arise.
1 - If the window is on another virtual desktop, that is, it is invisible, imlib generates an error.
2- The window cannot be below another. You have to bring it to the front to capture the image, how does the option `-b`
With that in mind, something like this would be better for me:
`wmctrl -i -a $WINDOWID && scrot -u`

```
-a <WIN>
   Switch to the desktop containing the window <WIN>, raise the window, and give it focus.
```

**Comment by peterbillam** [comment]
OK, good points. Perhaps that `wmctrl -i -a $WINDOWID && scrot -u` trick could be mentioned in the man page ? It's a good trick :-)

**Comment by daltomi** [comment]
Well, in the `manpage`, examples of using the options are shown, not tricks. :-) 
If we start placing tricks, everyone will want to send their own.
But it's my opinion only, if you send a PR and the community accepts it, everything is fine.

**Comment by ifohancroft** [comment]
I think it may be useful to utilize the Wiki section of the repo and add content there, with there being a page for certain tricks or maybe an FAQ page of sorts, answering How do I do [x,y,z]?
