### ISSUE TITLE
screenshot of a 10bpc screen comes out 8bit

### ISSUE THREAD

**Issue by guijan** [resurrecting-open-source-projects/scrot#344]
X11 and Xorg have 10bpc support, but a screenshot of such a screen will come out 8bpc. Imlib seems to deal exclusively with 8bpc colors.

**Comment by N-R-K** [comment]
I don't think this is actionable from scrot's end. You'll need to open an imlib2 issue about it.

**Comment by guijan** [comment]
Well, imlib2 said they can't add support for it. Supporting 10bit and more someday would mean using a different library.

**Comment by N-R-K** [comment]
> imlib2 said they can't add support for it.

Link to the [relevant discussions](https://git.enlightenment.org/old/legacy-imlib2/issues/12) for archiving/future-reference purposes.
