### ISSUE TITLE
build failure on SmartOS and other Solaris-based systems due to `dprintf`

### ISSUE THREAD

**Issue by guijan** [resurrecting-open-source-projects/scrot#346]
SmartOS is a fork of Illumos (itself a fork of Solaris). pkgsrc's automated testing shows 1.10 doesn't compile on SmartOS because it doesn't have a `dprintf()`:
https://us-central.manta.mnx.io/pkgsrc/public/reports/upstream-trunk/20230616.2249//scrot-1.10/build.log
https://bulktracker.appspot.com/pkg/ag1zfmJ1bGt0cmFja2VyciILEgVidWlsZBiAgICjiOXCCwwLEgNwa2cYgICAs7S--gkM

Illumos has online documentation, there's no `dprintf()` there, so we're broken on Illumos also: https://illumos.org/man/3C/all
It's likely the same is true for Solaris, but it seems their web conversion of the man pages is broken: https://docs.oracle.com/cd/E19253-01/817-0550/euqfl/index.html.

**Comment by N-R-K** [comment]
The `dprintf` was added in 1.9 though, not 1.10.

**Comment by guijan** [comment]
It appears the releases had so little time between them that 1.9 didn't get a build.
