### ISSUE TITLE
lack of information when scrot renames the output file because it already exists

### ISSUE THREAD

**Issue by guijan** [resurrecting-open-source-projects/scrot#350]
Okay, the default is to not overwrite, but this really should ~~error~~ print an informative message that the output filename was changed instead of silently succeeding as if nothing unexpected happened:
```sh
touch test.jpg
scrot test.jpg
```
The script above will create a _test_000.jpg_ file.

**Comment by guijan** [comment]
Man, sorry, I should stop making bug reports sleepy.

**Comment by N-R-K** [comment]
This is something that tripped me up a couple times too. IMO we should really print something to stderr if we decide to change the output file - *most* other programs that have similar behaviour seem to print something about not overwriting the existing file.

**Comment by guijan** [comment]
Reopened.
