### ISSUE TITLE
Scrot leaves visual artifacts in screen and the screenshots when using composite

### ISSUE THREAD

**Issue by Thanatermesis** [resurrecting-open-source-projects/scrot#36]
This issue happens specially when the desktop is using tear-free updates (vsync)

Detailed explanation of how and why scrot leaves these visual traces to the composite communication layer explained here:  

https://phab.enlightenment.org/T8552

Screenshot of the issue:

 ![artifacts](https://forum.elivelinux.org/uploads/default/original/2X/4/48397bbb30f46e57801971b720029d1effcb0625.png)

**Comment by megitu** [comment]
Using the option -f solved this issue on my PC.
`scrot -f -s`

**Comment by daltomi** [comment]
Close, commit 94e9696

**Comment by OliverLew** [comment]
@daltomi Just found this fix now, but in my case it is still having artifacts when any UI is updating, e.g., terminal output, browser loading, cursor blinking.

Versions of tested programs:
scrot: 20dac62d476d3438baff26d3d765e50622f408d9, current git master
picom: https://github.com/yshui/picom/tree/d974367a0446f4f1939daaada7cb6bca84c893ef, also latest git
xcompmgr: 1.1.8-2 in Arch Linux repository

This is when no compositor or xcompmgr, or `picom --backend xrender`, running `scrot -s`
![scrot-nocompositing](https://user-images.githubusercontent.com/12032219/103155207-55a02a00-47d8-11eb-92af-f93c0fc044e4.gif)

This is when `picom --backend glx`, running `scrot -s`, on the screen I can see color (mostly green) filling these lines but absent on screen recording
![scrot-picom-glx](https://user-images.githubusercontent.com/12032219/103155209-589b1a80-47d8-11eb-85e2-3de16ddb5b55.gif)

**Comment by daltomi** [comment]
Sorry, I didn't make it clear why I closed this issue.
I take it for solved because now there are 2 selection modes: `classic` and  `edge`
`scrot --select --line mode=edge`

`edge` mode would solve this problem. See screenshot: https://github.com/resurrecting-open-source-projects/scrot/pull/62#issuecomment-724778506

**Comment by OliverLew** [comment]
Yes, edge mode works.

But why not make that default and deprecate the classic mode, as in my tests the classic mode is almost not usable in a lot of occasions.
