### ISSUE TITLE
--freeze by default, when using scrot -s

### ISSUE THREAD

**Issue by Anonim19992** [resurrecting-open-source-projects/scrot#373]
Switched to the BSPWM environment. I noticed that when you just use scrot -s, there are often streaks (shown in the screenshot). I noticed that in other applications for creating screenshots, at the moment of "cutting" the moment into the screenshot, the picture itself freezes. After reviewing man, I saw that --freeze is present and supported in scrot. Why won't this api be connected to -s?
There is no difference, picom, compton, etc. are used.

![2023-12-02-202358_721x517_scrot](https://github.com/resurrecting-open-source-projects/scrot/assets/43230744/390db1e6-9fd9-49f4-9d56-bd978d8a48bd)

**Comment by N-R-K** [comment]
It's because `--freeze` (at least the way it's implemented in scrot) is quite hacky and can cause problems with certain software. See the faq on this https://github.com/resurrecting-open-source-projects/scrot/blob/master/FAQ.md#why-isnt-the---freeze-option-enabled-by-default

**Comment by mutageneral** [comment]
Instead of using --freeze, can we fix the visual bug of the selection border?

**Comment by N-R-K** [comment]
> Instead of using --freeze, can we fix the visual bug of the selection border?

`--line mode=edge` should fix the borders getting caught in the screenshot. Edge mode has other bugs when compositor is active: https://github.com/resurrecting-open-source-projects/scrot/issues/76 which is why it's not the unconditional default.
