### ISSUE TITLE
How to save screenshots to a specific directory

### ISSUE THREAD

**Issue by sathishmanohar** [resurrecting-open-source-projects/scrot#375]
I currently have my print screen key mapped to `scrot -z`. The screenshot files are created under the home directory. I want to specify the screenshots directory so that the files are created under `~/Screenshots/` How to specify target directory like that? I couldn't figure it out from the help command.

**Comment by N-R-K** [comment]
`scrot` accepts filename as argument. So `scrot ~/Screenshot/shot.png` would work. If you want a timestamp of each screenshot then something like `scrot ~/Screenshot/%F_%T.png` would work.

Consult the scrot manpage for further details.
