### ISSUE TITLE
Scrot screenshot outputs black image on Raspberry Pi

### ISSUE THREAD

**Issue by JacobHagberg** [resurrecting-open-source-projects/scrot#380]
The board is Pi4 Model B with 8 gigs of ram running Raspberry Pi OS. The command scrot command, when run, simply outputs a png that contains all black pixels. The image is in the size of the screen being captured.

**Comment by N-R-K** [comment]
What's the scrot version being used? Are you running X or wayland? Do other screenshot utilities work?

**Comment by JacobHagberg** [comment]
Just tried on one of my other Raspberry Pis, and it works on that one so this is probably an issue on my end. Sorry about that.
