### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by nick1981** [resurrecting-open-source-projects/scrot#383]
Hi Team,

I've just installed scrot on a fresh new Debian 12 system.

But when executing scrot without any option in the terminal, it creates a black screen.

How to overcome this? It was working properly on my two others computers, all Debian 12.

Below the system specs :

Chassis: desktop 🖥️
Operating System: Debian GNU/Linux 12 (bookworm)  
Kernel: Linux 6.1.0-21-amd64
Architecture: x86-64
Hardware Vendor: Hewlett-Packard
Hardware Model: HP ProDesk 400 G2 MT _TPM DP_
Firmware Version: L02 v02.39

scrot version 1.8.1

![2024-06-27-201632_1920x1080_scrot](https://github.com/resurrecting-open-source-projects/scrot/assets/5447682/70b8811e-4c42-4471-aadc-6e56adc1dbb4)

**Comment by N-R-K** [comment]
Is this using X11 or wayland?

**Comment by nick1981** [comment]
wayland

**Comment by nick1981** [comment]
well, you have shown me the path. i have switched to x11 and know it works... thank you !!!
![2024-07-03-scrot_1win_0](https://github.com/resurrecting-open-source-projects/scrot/assets/5447682/bb2fbc5f-33bf-4ddf-8fd5-a15bc176e518)
