### ISSUE TITLE
Is there any way to include the window name in the screenshot file name?

### ISSUE THREAD

**Issue by rootexpression** [resurrecting-open-source-projects/scrot#384]
I've been trying at this for a while, but all of the solutions use the now depreciated note option.
To clarify, this is taking a screenshot of the window currently with focus, and appending its title to the file name.

This is something that'd help a lot in sorting screenshots, and finding "that one" you needed.

**Comment by N-R-K** [comment]
> but all of the solutions use the now depreciated note option

Can you show an example of this? The note option draws text on the screenshot, it doesn't do any file renaming, so I'm not sure how it's solving your issue here.

**Comment by N-R-K** [comment]
> To clarify, this is taking a screenshot of the window currently with focus, and appending its title to the file name.

The `%W` should do what you're looking for, based on this description. E.g 

```console
$ scrot -u 'shot $W.png'
```

See the manpage for more special specifies in filenames like this.

(I'm not sure how or where the note option is coming into play here. These special specifiers aren't tied to note option.)
