### ISSUE TITLE
Using `.jpeg` extension doesn't work if file already exists

### ISSUE THREAD

**Issue by pekkaklarck** [resurrecting-open-source-projects/scrot#51]
To reproduce:

```
$ scrot example.jpeg
$ scrot example.jpeg
giblib error: Saving to file example.jpeg_000 failed
```

Apparently the code to avoid overwriting the file introduced by #12/#15 doesn't work too well in this case. As discussed in #30, avoiding overwriting may not be the best default behavior in the first place.

**Comment by dormail** [comment]
There is an overwrite option
`$ scrot example.jpeg`
`$ scrot example.jpeg -o`
works for me.
