### ISSUE TITLE
Fix for CFI Violation

### ISSUE THREAD

**Issue by lattera** [resurrecting-open-source-projects/scrot#71]
Scrot version 1.5 introduced a small Control-Flow Integrity (CFI) violation. Specifically, the cfi-icall scheme was violated. I've fixed it in my fork of scrot on HardenedBSD's self-hosted GitLab: https://git.hardenedbsd.org/shawn.webb/scrot/-/commit/0f1728e323d5250936b00678c73abdc26d204546

I've also attached the patch to this issue.

[scrot.patch.txt](https://github.com/resurrecting-open-source-projects/scrot/files/6158647/scrot.patch.txt)

**Comment by daltomi** [comment]
Thanks.
