### ISSUE TITLE
selection tool leaves rectangle trails

### ISSUE THREAD

**Issue by phord** [resurrecting-open-source-projects/scrot#74]
First time using scrot.  I built it from master and tried it for the first time. I used the --select option.  

Mouse changed to crosshair cursor.  I clicked and dragged to define a region to capture.  As I did, the bounding box left behind trails where it did not erase cleanly.  These were captured in the screenshot that was saved, as well.

I tried building earlier versions (back to 0.9) and the bug exists in every version tried.  It also exists in the distro version (1.2) installed with apt.

Linux Mint 20.1 MATE (Gnome2) w/ marco compositor, 4k monitors

I've seen this exact sort of bug before.  It's usually caused by "erasing" a rectangle at a different size than was originally drawn.

Seems weird if I'm the only one seeing it, so I suspect some unusual graphics config is interacting poorly.

![2021-03-20-180900_865x604_scrot](https://user-images.githubusercontent.com/123908/111890569-d4f06480-89a7-11eb-8a35-ae25b0f305d6.png)

**Comment by phord** [comment]
Similar to what was [reported here](https://bbs.archlinux.org/viewtopic.php?id=255083), though the issue is more dramatic for me.

Oh, bleh -- this is because scrot draws directly to the x buffers and the system is drawing to them at the same time?  Lame.  Using --freeze fixes the problem.  But it shouldn't be happening anyway by default.

Probably --select should not draw on a "live" display buffer at all.

Similar / related to https://github.com/dreamer/scrot/issues/2, probably.

**Comment by daltomi** [comment]
Hi 
Try:
`scrot --select --line mode=edge`

**Comment by phord** [comment]
Thanks, @daltomi .  I just stumbled across that in the code.  Not sure why I didn't see when I scanned closed issues earlier.

I find `mode=edge` to be buggy as well.  For some reason it leaves a preliminary rectangle on the screen in the top left corner of the capture.
![2021-03-20-192513_331x86_scrot](https://user-images.githubusercontent.com/123908/111891720-1c7bee00-89b2-11eb-9f80-b49fa3f2bf12.png)

**Comment by daltomi** [comment]
Does it only happen when you drag and drop very fast or always?

**Comment by phord** [comment]
Always, even if I click without moving the cursor at all, then move it several seconds later to create a non-zero sized rectangle.   In this case the dropped rectangle is small (1/4 size of a letter on my screen). If I click and drag quickly the rectangle is larger.

**Comment by phord** [comment]
Sometimes the rectangle is in the captured region, but sometimes it is not.
![2021-03-20-201300_135x96_scrot](https://user-images.githubusercontent.com/123908/111892502-484ea200-89b9-11eb-836d-23aee87f945a.png)

**Comment by daltomi** [comment]
I still do not know if it's a new bug or it's the one I have and I'm trying to solve. 
If you can test the PR #75

**Comment by daltomi** [comment]
I just installed Mate and I was able to observe the fault indicating.
I'll look.

**Comment by daltomi** [comment]
Hi @phord
I opened a new Issue #76 for the problem of MATE and I close this one that partially solves it with: `scrot --select --freeze`

**Comment by phord** [comment]
Thanks for looking into this. I was planning to explore it some myself, but I don't know how much time I'll have to play with scrot in the end.

**Comment by phord** [comment]
I do think the original problem (fixed by freeze) should be properly fixed so freeze is no longer necessary. A happy medium might be too make freeze the default mode.
