### ISSUE TITLE
unable to select 1px at the right size of the screen

### ISSUE THREAD

**Issue by AtifChy** [resurrecting-open-source-projects/scrot#77]
![image](https://user-images.githubusercontent.com/42291930/112671371-46d71b00-8e8c-11eb-8312-48a539a61a60.png)
look at the border of my bar. it's missing border at the right side because I am unable to select that area with scrot -s.

**Comment by daltomi** [comment]
Hi all.
If I understand correctly, the bar covers the width of the screen.
Then the problem happens when the selection cursor reaches the maximum width.
I created a PR that should correct this problem. Please test it.

**Comment by AtifChy** [comment]
@daltomi it doesn't fix the problem

**Comment by AtifChy** [comment]
@daltomi it works
