### ISSUE TITLE
[Feature request] Open screenshot in

### ISSUE THREAD

**Issue by ifohancroft** [resurrecting-open-source-projects/scrot#83]
It would be awesome if scrot has an option to provide an image viewer (or you can pass xdg-open as a parameter for a more "portable" approach) to open the screenshot in.

I know the -e option exists and it can be used for that, but sometimes you might want to upload the screenshot and view it at the same time and that option would allow that.

I admit, that I haven't tried stacking -e options, so I don't know if that's possible, but either way, I feel like a dedicated open option, besides the execute option, would be the best solution.

**Comment by StarPlatin4m** [comment]
I feel the `-e` solves your problem perfectly
For example:
```
scrot -s $HOME/'Pictures/Screenshots/%Y-%m-%d_%H%M%S-$wx$h_scrot.png' -e 'xclip -selection clipboard -target image/png -i $f; xdg-open $f'
```

Will copy your image to the clipboard and open it in your default viewer. You can just replace my clipboard command with whatever code you use to upload.

Just divide your commands using ";" and "&&" where necessary, add "&" to run each command in a different thread. All within the quotes of the `-e`

**Comment by ifohancroft** [comment]
Thanks! It's good to know this is possible. Still though, a dedicated parameter for opening would be the most ideal.

**Comment by peterwu** [comment]
Well, I guess it comes to the good old UNIX philosophy: “Do one thing, and do it well.”

scrot is screenshot taker and I don't think it should mess with the picture viewing business. Leave that to other dedicated programs, such as feh. 

Just my 2 cents.

**Comment by ifohancroft** [comment]
> Well, I guess it comes to the good old UNIX philosophy: “Do one thing, and do it well.”
> 
> scrot is screenshot taker and I don't think it should mess with the picture viewing business. Leave that to other dedicated programs, such as feh.
> 
> Just my 2 cents.

I agree with you, but just to clarify: I don't want scrot to pen the image for me. I want to be able to pass a program name as a parameter that will cause scrot to send the image to that program so the program can open the image. I mean heck, even just passing an option, without any value, and the presence of that option causing scrot to pass the image to xdg-open would be nice
